version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mova_db
      POSTGRES_USER: mova_user
      POSTGRES_PASSWORD: mova_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: